Starting cloudmanager as cloudmanager
[2016-03-14 19:40:32 +0000] [1780] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f5d8dcabb90>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f5d8dcab8c0>
  pre_fork: <function pre_fork at 0x7f5d8dcaba28>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: cloudmanager
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f5d8dcab758>
  pre_exec: <function pre_exec at 0x7f5d8dcb01b8>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f5d8dcabcf8>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f5d8dcb0848>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f5d8dcb0320>
  post_request: <function post_request at 0x7f5d8dcb0410>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f5d8dcabe60>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f5d8dcb0578>
  chdir: /home/cloudmanager/Cloud-Deployment-Utility/cloudmanager
  paste: None
  default_proc_name: cloudmanager.wsgi:application
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f5d8dcab5f0>
  worker_abort: <function worker_abort at 0x7f5d8dcb0050>
  bind: ['unix:/home/cloudmanager/Cloud-Deployment-Utility/cloudmanager/run/gunicorn.sock']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f5d8dcb06e0>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2016-03-14 19:40:32 +0000] [1780] [INFO] Starting gunicorn 19.4.5
[2016-03-14 19:40:32 +0000] [1780] [DEBUG] Arbiter booted
[2016-03-14 19:40:32 +0000] [1780] [INFO] Listening at: unix:/home/cloudmanager/Cloud-Deployment-Utility/cloudmanager/run/gunicorn.sock (1780)
[2016-03-14 19:40:32 +0000] [1780] [INFO] Using worker: sync
[2016-03-14 19:40:32 +0000] [1791] [INFO] Booting worker with pid: 1791
[2016-03-14 19:40:32 +0000] [1794] [INFO] Booting worker with pid: 1794
[2016-03-14 19:40:32 +0000] [1795] [INFO] Booting worker with pid: 1795
[2016-03-14 19:40:32 +0000] [1780] [DEBUG] 3 workers
[2016-03-14 23:52:21 +0000] [1794] [DEBUG] GET /
[2016-03-14 23:52:22 +0000] [1795] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-03-14 23:52:39 +0000] [1794] [DEBUG] GET /
[2016-03-14 23:54:42 +0000] [1794] [DEBUG] GET /
[2016-03-14 23:54:49 +0000] [1795] [DEBUG] GET /
[2016-03-14 23:54:49 +0000] [1791] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-03-14 23:55:03 +0000] [1795] [DEBUG] GET /
[2016-03-14 23:55:04 +0000] [1794] [DEBUG] GET /favicon.ico
Not Found: /favicon.ico
[2016-03-14 23:59:15 +0000] [1791] [DEBUG] GET /
